[package]
name = "aether_ai"
version = "1.0.0"
authors = ["AetherAI"]

[addresses]
aether_ai = "0x67043cfd9027a5ccf7078fbbbdd2ff4f88d3f7ebf754819e472c2360328f1a5b"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
